version: '3.8'

services:
  app:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=alejandro
      - POSTGRES_PASSWORD=new_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: